baseurl = "http://lasp-lang.github.io"
languageCode = "en-us"
title = "Partisan"

[params]
    description = "High-performance geo-distributed Erlang and Elixir"
    author_url = "http://christophermeiklejohn.com"
    author = "Christopher Meiklejohn"
    project_url = "http://github.com/lasp-lang/partisan"
    project_documentation = "http://lasp-lang.github.io"
    github_project_name = "partisan"
    github_user_name = "lasp-lang"

    first_color="#f8f8f8"
    first_border_color="#e7e7e7"
    first_text_color="#333"

    second_color="white"
    second_text_color="#333"

    header_color="#f8f8f8"
    header_text_color="rgb(51, 51, 51)"

    header_link_color="#777"
    header_link_hover_color="rgb(51, 51, 51)"